### ISSUE TITLE
IPN URL is URL to modules/gateways/callback/payiota.php ?

### ISSUE THREAD

**Issue by slrslr** [lacicloud/payiota-whmcs#1]
Hello, in my https://payiota.me account i see "No IPN URL Added".
I wonder if i should add https://mywhmcs.com/modules/gateways/callback/payiota.php
?

In docs they say:

> 9. IPN
> 
> When an invoice is paid (meaning the address has a balance equal or more than that of the 1th place in the response when you generated the invoice), our server will send you a POST request with the following variables:
> 
> address : The IOTA address the user paid to
> 
> realID : Your ID
> 
> price : Price in USD
> 
> price_iota : Price in IOTA
> 
> custom : Your custom string
> 
> ipn_url : Your IPN URL

**Comment by lacicloud** [comment]
Hey,

That is not necessary anymore, as the WHMCS plugin code automatically adds it and PayIOTA.me now supports dynamic IPNs.

Best,
Laszlo
